name: web_gl
description: An absolute bare-bones web app.
version: 1.0.0+2

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  lints: ^1.0.1
