name: web_gl
description: An absolute bare-bones web app.
version: 1.0.0+1

environment:
  sdk: '>=2.14.0-0 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  lints: ^1.0.0
